In [1]:
import pandas as pd

In [2]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is 2E3D-90D7

 Directory of C:\Users\LENOVO\Desktop\pandas

06/29/2024  11:22 AM    <DIR>          .
06/28/2024  01:42 PM    <DIR>          ..
06/29/2024  11:21 AM    <DIR>          .ipynb_checkpoints
06/29/2024  09:50 AM                48 11Tes2t.csv
06/29/2024  09:47 AM                45 5T2es2t.csv
06/29/2024  09:47 AM                45 aaa5T2es2t.csv
06/28/2024  10:36 PM            13,658 Dataframe_in_pandas.ipynb
06/28/2024  10:44 PM            12,820 insert_and_deletepandas.ipynb
06/28/2024  01:55 PM             4,191 PANDAS1.ipynb
06/29/2024  09:52 AM             3,813 pandaswithcsv.ipynb
06/19/2024  07:30 AM               988 president_heights.csv
06/29/2024  11:21 AM                72 read_with_csv.ipynb
06/28/2024  08:01 PM             6,509 series_in_pandas.ipynb
06/29/2024  09:46 AM                45 T2es2t.csv
06/29/2024  09:50 AM                48 Tes2t.csv
06/29/2024  09:46 AM                45 Test.csv
06/29/2024  09:45 AM                36 Test.csv2
              14 File(s)         42,363 bytes
               3 Dir(s)  187,099,566,080 bytes free

In [3]:
pd.read_csv("president_heights.csv")

    order                    name  height(cm)
0       1       George Washington         189
1       2              John Adams         170
2       3        Thomas Jefferson         189
3       4           James Madison         163
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
7       8        Martin Van Buren         168
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur         183
21     23       Benjamin Harrison         168
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
24     27     William Howard Taft         182
25     28          Woodrow Wilson         180
26     29       Warren G. Harding         183
27     30         Calvin Coolidge         178
28     31          Herbert Hoover         182
29     32   Franklin D. Roosevelt         188
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
32     35         John F. Kennedy         183
33     36       Lyndon B. Johnson         193
34     37           Richard Nixon         182
35     38             Gerald Ford         183
36     39            Jimmy Carter         177
37     40           Ronald Reagan         185
38     41       George H. W. Bush         188
39     42            Bill Clinton         188
40     43          George W. Bush         182
41     44            Barack Obama         185

In [4]:
pd.read_csv("president_heights.csv",nrows=1)

   order               name  height(cm)
0      1  George Washington         189

In [5]:
pd.read_csv("president_heights.csv",usecols=['name'])

                      name
0        George Washington
1               John Adams
2         Thomas Jefferson
3            James Madison
4             James Monroe
5        John Quincy Adams
6           Andrew Jackson
7         Martin Van Buren
8   William Henry Harrison
9               John Tyler
10           James K. Polk
11          Zachary Taylor
12        Millard Fillmore
13         Franklin Pierce
14          James Buchanan
15         Abraham Lincoln
16          Andrew Johnson
17        Ulysses S. Grant
18     Rutherford B. Hayes
19       James A. Garfield
20       Chester A. Arthur
21       Benjamin Harrison
22        William McKinley
23      Theodore Roosevelt
24     William Howard Taft
25          Woodrow Wilson
26       Warren G. Harding
27         Calvin Coolidge
28          Herbert Hoover
29   Franklin D. Roosevelt
30         Harry S. Truman
31    Dwight D. Eisenhower
32         John F. Kennedy
33       Lyndon B. Johnson
34           Richard Nixon
35             Gerald Ford
36            Jimmy Carter
37           Ronald Reagan
38       George H. W. Bush
39            Bill Clinton
40          George W. Bush
41            Barack Obama

In [7]:
pd.read_csv("president_heights.csv",usecols=[0,1])

    order                    name
0       1       George Washington
1       2              John Adams
2       3        Thomas Jefferson
3       4           James Madison
4       5            James Monroe
5       6       John Quincy Adams
6       7          Andrew Jackson
7       8        Martin Van Buren
8       9  William Henry Harrison
9      10              John Tyler
10     11           James K. Polk
11     12          Zachary Taylor
12     13        Millard Fillmore
13     14         Franklin Pierce
14     15          James Buchanan
15     16         Abraham Lincoln
16     17          Andrew Johnson
17     18        Ulysses S. Grant
18     19     Rutherford B. Hayes
19     20       James A. Garfield
20     21       Chester A. Arthur
21     23       Benjamin Harrison
22     25        William McKinley
23     26      Theodore Roosevelt
24     27     William Howard Taft
25     28          Woodrow Wilson
26     29       Warren G. Harding
27     30         Calvin Coolidge
28     31          Herbert Hoover
29     32   Franklin D. Roosevelt
30     33         Harry S. Truman
31     34    Dwight D. Eisenhower
32     35         John F. Kennedy
33     36       Lyndon B. Johnson
34     37           Richard Nixon
35     38             Gerald Ford
36     39            Jimmy Carter
37     40           Ronald Reagan
38     41       George H. W. Bush
39     42            Bill Clinton
40     43          George W. Bush
41     44            Barack Obama

In [9]:
pd.read_csv("president_heights.csv",skiprows=[0])

     1       George Washington  189
0    2              John Adams  170
1    3        Thomas Jefferson  189
2    4           James Madison  163
3    5            James Monroe  183
4    6       John Quincy Adams  171
5    7          Andrew Jackson  185
6    8        Martin Van Buren  168
7    9  William Henry Harrison  173
8   10              John Tyler  183
9   11           James K. Polk  173
10  12          Zachary Taylor  173
11  13        Millard Fillmore  175
12  14         Franklin Pierce  178
13  15          James Buchanan  183
14  16         Abraham Lincoln  193
15  17          Andrew Johnson  178
16  18        Ulysses S. Grant  173
17  19     Rutherford B. Hayes  174
18  20       James A. Garfield  183
19  21       Chester A. Arthur  183
20  23       Benjamin Harrison  168
21  25        William McKinley  170
22  26      Theodore Roosevelt  178
23  27     William Howard Taft  182
24  28          Woodrow Wilson  180
25  29       Warren G. Harding  183
26  30         Calvin Coolidge  178
27  31          Herbert Hoover  182
28  32   Franklin D. Roosevelt  188
29  33         Harry S. Truman  175
30  34    Dwight D. Eisenhower  179
31  35         John F. Kennedy  183
32  36       Lyndon B. Johnson  193
33  37           Richard Nixon  182
34  38             Gerald Ford  183
35  39            Jimmy Carter  177
36  40           Ronald Reagan  185
37  41       George H. W. Bush  188
38  42            Bill Clinton  188
39  43          George W. Bush  182
40  44            Barack Obama  185

In [12]:
pd.read_csv('president_heights.csv',index_col=['name'])

                        order  height(cm)
name
George Washington           1         189
John Adams                  2         170
Thomas Jefferson            3         189
James Madison               4         163
James Monroe                5         183
John Quincy Adams           6         171
Andrew Jackson              7         185
Martin Van Buren            8         168
William Henry Harrison      9         173
John Tyler                 10         183
James K. Polk              11         173
Zachary Taylor             12         173
Millard Fillmore           13         175
Franklin Pierce            14         178
James Buchanan             15         183
Abraham Lincoln            16         193
Andrew Johnson             17         178
Ulysses S. Grant           18         173
Rutherford B. Hayes        19         174
James A. Garfield          20         183
Chester A. Arthur          21         183
Benjamin Harrison          23         168
William McKinley           25         170
Theodore Roosevelt         26         178
William Howard Taft        27         182
Woodrow Wilson             28         180
Warren G. Harding          29         183
Calvin Coolidge            30         178
Herbert Hoover             31         182
Franklin D. Roosevelt      32         188
Harry S. Truman            33         175
Dwight D. Eisenhower       34         179
John F. Kennedy            35         183
Lyndon B. Johnson          36         193
Richard Nixon              37         182
Gerald Ford                38         183
Jimmy Carter               39         177
Ronald Reagan              40         185
George H. W. Bush          41         188
Bill Clinton               42         188
George W. Bush             43         182
Barack Obama               44         185

In [13]:
pd.read_csv('president_heights.csv',header=2)

     2              John Adams  170
0    3        Thomas Jefferson  189
1    4           James Madison  163
2    5            James Monroe  183
3    6       John Quincy Adams  171
4    7          Andrew Jackson  185
5    8        Martin Van Buren  168
6    9  William Henry Harrison  173
7   10              John Tyler  183
8   11           James K. Polk  173
9   12          Zachary Taylor  173
10  13        Millard Fillmore  175
11  14         Franklin Pierce  178
12  15          James Buchanan  183
13  16         Abraham Lincoln  193
14  17          Andrew Johnson  178
15  18        Ulysses S. Grant  173
16  19     Rutherford B. Hayes  174
17  20       James A. Garfield  183
18  21       Chester A. Arthur  183
19  23       Benjamin Harrison  168
20  25        William McKinley  170
21  26      Theodore Roosevelt  178
22  27     William Howard Taft  182
23  28          Woodrow Wilson  180
24  29       Warren G. Harding  183
25  30         Calvin Coolidge  178
26  31          Herbert Hoover  182
27  32   Franklin D. Roosevelt  188
28  33         Harry S. Truman  175
29  34    Dwight D. Eisenhower  179
30  35         John F. Kennedy  183
31  36       Lyndon B. Johnson  193
32  37           Richard Nixon  182
33  38             Gerald Ford  183
34  39            Jimmy Carter  177
35  40           Ronald Reagan  185
36  41       George H. W. Bush  188
37  42            Bill Clinton  188
38  43          George W. Bush  182
39  44            Barack Obama  185

In [14]:
pd.read_csv("president_heights.csv",names=['col1','col2','col3'])

     col1                    col2        col3
0   order                    name  height(cm)
1       1       George Washington         189
2       2              John Adams         170
3       3        Thomas Jefferson         189
4       4           James Madison         163
5       5            James Monroe         183
6       6       John Quincy Adams         171
7       7          Andrew Jackson         185
8       8        Martin Van Buren         168
9       9  William Henry Harrison         173
10     10              John Tyler         183
11     11           James K. Polk         173
12     12          Zachary Taylor         173
13     13        Millard Fillmore         175
14     14         Franklin Pierce         178
15     15          James Buchanan         183
16     16         Abraham Lincoln         193
17     17          Andrew Johnson         178
18     18        Ulysses S. Grant         173
19     19     Rutherford B. Hayes         174
20     20       James A. Garfield         183
21     21       Chester A. Arthur         183
22     23       Benjamin Harrison         168
23     25        William McKinley         170
24     26      Theodore Roosevelt         178
25     27     William Howard Taft         182
26     28          Woodrow Wilson         180
27     29       Warren G. Harding         183
28     30         Calvin Coolidge         178
29     31          Herbert Hoover         182
30     32   Franklin D. Roosevelt         188
31     33         Harry S. Truman         175
32     34    Dwight D. Eisenhower         179
33     35         John F. Kennedy         183
34     36       Lyndon B. Johnson         193
35     37           Richard Nixon         182
36     38             Gerald Ford         183
37     39            Jimmy Carter         177
38     40           Ronald Reagan         185
39     41       George H. W. Bush         188
40     42            Bill Clinton         188
41     43          George W. Bush         182
42     44            Barack Obama         185

In [28]:
a=pd.read_csv("president_heights.csv",header=None)

In [30]:
a.add_prefix('col')

     col0                    col1        col2
0   order                    name  height(cm)
1       1       George Washington         189
2       2              John Adams         170
3       3        Thomas Jefferson         189
4       4           James Madison         163
5       5            James Monroe         183
6       6       John Quincy Adams         171
7       7          Andrew Jackson         185
8       8        Martin Van Buren         168
9       9  William Henry Harrison         173
10     10              John Tyler         183
11     11           James K. Polk         173
12     12          Zachary Taylor         173
13     13        Millard Fillmore         175
14     14         Franklin Pierce         178
15     15          James Buchanan         183
16     16         Abraham Lincoln         193
17     17          Andrew Johnson         178
18     18        Ulysses S. Grant         173
19     19     Rutherford B. Hayes         174
20     20       James A. Garfield         183
21     21       Chester A. Arthur         183
22     23       Benjamin Harrison         168
23     25        William McKinley         170
24     26      Theodore Roosevelt         178
25     27     William Howard Taft         182
26     28          Woodrow Wilson         180
27     29       Warren G. Harding         183
28     30         Calvin Coolidge         178
29     31          Herbert Hoover         182
30     32   Franklin D. Roosevelt         188
31     33         Harry S. Truman         175
32     34    Dwight D. Eisenhower         179
33     35         John F. Kennedy         183
34     36       Lyndon B. Johnson         193
35     37           Richard Nixon         182
36     38             Gerald Ford         183
37     39            Jimmy Carter         177
38     40           Ronald Reagan         185
39     41       George H. W. Bush         188
40     42            Bill Clinton         188
41     43          George W. Bush         182
42     44            Barack Obama         185